### ISSUE TITLE
证书的运行错误。

### ISSUE THREAD

**Issue by theoneLee** [EDDYCJY/grpc-hello-world#6]
按照 https://eddycjy.com/posts/go/grpc-gateway/2018-02-27-hello-world/ 跟着敲一遍，但是启动有一个报错：

```bash
edzdeMacBook-Pro:grpc_gw_demo edz$ go run main.go server
2020/06/11 17:59:31 gRPC and https listen on: 50052
2020/06/11 17:59:31 http: TLS handshake error from 127.0.0.1:54533: remote error: tls: bad certificate
2020/06/11 17:59:32 http: TLS handshake error from 127.0.0.1:54534: remote error: tls: bad certificate
2020/06/11 17:59:33 http: TLS handshake error from 127.0.0.1:54535: remote error: tls: bad certificate
```

看了下你这里更新的commit （ https://github.com/eddycjy/grpc-hello-world/commit/12331fde3797d53c238c86467d7b68c0188154c6 ），里面有 `server-key.pem` ，请问这个是怎么生成的？使用这个`server-key.pem` 就可以解决demo启动报错的问题么？

thx。

**Comment by theoneLee** [comment]
可以的话。希望更新一下grpc的教程。thx。

**Comment by theoneLee** [comment]
或者你提供你这个文章的md文件给我或者建个仓，我调试通了，会改进文章的问题，然后提交一个pr。。

**Comment by fafucoder** [comment]
@theoneLee 填写Common Name 需要一致，就不会报这个错了
![image](https://user-images.githubusercontent.com/16442491/96670300-8fe0eb80-1391-11eb-9671-5a4fb022c232.png)

**Comment by 654356282** [comment]
> @theoneLee 填写Common Name 需要一致，就不会报这个错了
> ![image](https://user-images.githubusercontent.com/16442491/96670300-8fe0eb80-1391-11eb-9671-5a4fb022c232.png)

没解决
